### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by darkdragon-001** [it-at-m/sps-frontend#12]
There is no `LICENSE` file in this repository. This makes it difficult for other to re-use the contents of this repository. See https://choosealicense.com/no-permission/ on why this is a problem.

**Comment by hupling** [comment]
Ich habe leider überhaupt keine Ahnung von Lizenzen und OpenSource Projekten. Das Projekt ist einfach zum Testen von Github Actions. Es ist ein Fork vom Beispiel-Projekt. Bei Gelegenheit schreibe ich das auch in die Readme.
